apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-python
  labels:
    app: demo-devops-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops-python
  template:
    metadata:
      labels:
        app: demo-devops-python
    spec:
      containers:
      - name: demo-devops-python
        image: registry.example.com/demo-devops-python:latest  # Actualiza con tu imagen
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            value: "8000"
          - name: DJANGO_SETTINGS_MODULE
            value: "demo_devops.settings"
        # Importa variables no sensibles desde el ConfigMap
        envFrom:
          - configMapRef:
              name: demo-devops-config
        # Variables sensibles definidas en Secrets
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: demo-devops-secret
                key: SECRET_KEY
        readinessProbe:
          httpGet:
            path: /api/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30

