name: CI

on:
  push:
    branches: [ main, feature/F1S1YCF ]
  pull_request:
    branches: [ main, feature/F1S1YCF ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myuser" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage

      # Aquí se copia el archivo .env.ci a .env
      - name: Setup .env for CI
        run: cp .env.ci .env

      # Esperar a que PostgreSQL esté listo
      - name: Wait for PostgreSQL
        run: |
          sudo apt-get update && sudo apt-get install -y netcat-openbsd
          echo "Esperando a que PostgreSQL esté disponible..."
          for i in {1..30}; do
            nc -z postgres 5432 && echo "PostgreSQL está listo" && exit 0 || sleep 2
          done
          echo "PostgreSQL no se activó en el tiempo esperado" && exit 1        

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test

      - name: Run flake8
        run: flake8 .

      - name: Run coverage
        run: |
          coverage run --source=. manage.py test
          coverage report
